#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/{nginx/site-confs,keys} \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx


# copy config files
tpl /defaults/nginx.conf > /config/nginx/nginx.conf


if [[ ! -f /config/nginx/web.conf ]]; then
    tpl /defaults/web.conf > /config/nginx/web.conf
fi

if [[ ! -f /config/nginx/ssl.conf ]]; then
    tpl /defaults/ssl.conf > /config/nginx/ssl.conf
fi

if [[ ! -f /config/nginx/site-confs/default ]]; then
    tpl /defaults/default > /config/nginx/site-confs/default
fi

tpl /defaults/keys/cert.crt > /config/keys/cert.crt

tpl /defaults/keys/cert.key > /config/keys/cert.key